### ISSUE TITLE
decks containing bilge water cards are not decoded

### ISSUE THREAD

**Issue by rickgxp** [Zmezmer/MightyPoro#2]
hello, first congratulations on the project, I'm not sure how to handle the github, forgive me if I sent you the wrong place. we used your bot in a discord and the question arose if it is a bug in the decks with new cards not being decoded, will the bot be updated? sorry for the inconvenience and thanks in advance!

**Comment by Zmezmer** [comment]
You’re on the wrong GitHub page. You’re looking for a different bot. This one doesn’t have Legends of Runeterra.

**Comment by rickgxp** [comment]
forgiveness for the mistake
